### ISSUE TITLE
Dynamically Menu creation

### ISSUE THREAD

**Issue by jmvalim** [kybarg/bootstrap-dropdown-hover#17]
When creating the dropdown and items dynamically, the menu does not perform as expected. Looking at the code, javascript traverses the items when the document is ready. Is there any way to do this through a function call?

Thanks in advance

**Comment by kybarg** [comment]
You can initiate it with `$('.dropdown-toggle').dropdownhover()`

**Comment by jmvalim** [comment]
Hi, the hover is working, but the menu second level is not showing. Could you help me?

Thanks in advance.

![image](https://user-images.githubusercontent.com/5316030/39414311-613fcca0-4c0c-11e8-8c6e-94723f94d174.png)
