### ISSUE TITLE
Breakpoints in script do not match css media queries

### ISSUE THREAD

**Issue by acnp77** [kybarg/bootstrap-dropdown-hover#18]
The 2 instances of `if($(window).width() >= 768)` do not always match the css media queries used in bootstrap (because of the different handling of the scrollbar in different browsers)

EXAMPLE: Open your demo in Chrome Browser and set the windows width to 768px. The dropdown works. Now reduce the window height so scrollbars appear. Then the dropdown does not work anymore.

I changed `if($(window).width() >= 768)`
to `var xx = window.matchMedia("(min-width: 768px)")
if( xx.matches )`

So now the js and css width's should always match.

Thanks for the great script, really nice.
Cheers

**Comment by kybarg** [comment]
Switched to detection of mobile devices and applying different logic for touchscreens
